name: "Prepare klogg version env var"
description: ""
runs:
  using: "composite"
  steps:
    - name: Set klogg version
      shell: sh
      run: |
        echo "KLOGG_VERSION=26.08.0.$((${{ github.run_number }} + 0))" >> $GITHUB_ENV 
